matrix:
  include:
    - rvm: 2.2.7
    - rvm: 2.3.4
    - rvm: 2.4.1  
    - rvm: jruby-9.1.10.0
      jdk: oraclejdk8
      env:
        - JRUBY_OPTS=--debug
before_install:
  - gem install bundler
cache:
  - bundler  
dist: trusty
sudo: false
